site_name: multipoles Docs

plugins:
  - mkdocstrings:

theme:
  name: "readthedocs"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'Home': index.md
  - usage.md
  - theory.md
  - 'API Reference': reference.md